# Generated by Django 3.0.4 on 2020-07-14 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgen', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
