# Generated by Django 3.0.8 on 2020-07-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgen', '0009_auto_20200727_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='image_1',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
