# Generated by Django 3.0.8 on 2020-07-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgen', '0010_auto_20200727_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='filepath',
        ),
    ]
