# Generated by Django 3.0.8 on 2020-07-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgen', '0012_auto_20200727_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='filepath',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='art',
            name='image_1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='art',
            name='image_2',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
