# Generated by Django 3.0.8 on 2020-08-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgen', '0013_auto_20200728_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
