# Generated by Django 3.0.8 on 2020-08-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgen', '0014_like_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
