# Generated by Django 3.0.8 on 2020-08-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgen', '0015_auto_20200818_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='number',
        ),
        migrations.AddField(
            model_name='art',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
